name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --max-line-length=79 --const-naming-style=any --disable=R1721,R0903,C0303,E1101,R1716,E0401,W1514,C0200,C0114,C0301,E0602,W0104,C0302,R0801,E1136,line-too-long,C0305,E2515 --disable=import-error $(git ls-files '*.py' '*.ipynb')
        nbqa pylint --max-line-length=79 --const-naming-style=any --disable=R1721,R0903,E2515,C0303,E1101,R1716,E0401,W1514,C0200,C0114,C0301,E0602,W0104,C0302,R0801,E1136,C0305,E2515 --disable=import-error $(git ls-files '*.py' '*.ipynb')
